### ISSUE TITLE
What's the improvement of this compared to core Translate behaviour?

### ISSUE THREAD

**Issue by Spriz** [AD7six/cakephp-shadow-translate#15]
Hey!

Compared to: http://book.cakephp.org/3.0/en/orm/behaviors/translate.html#using-a-separate-translations-table

Could you explain reason(s) for using this instead? :smile: I see it's stated as more "effective" - but how is that?

Thanks!

**Comment by AD7six** [comment]
Good question. I thought this was already covered, I'll add some info to the docs to explain in more details.

If you use the core behavior on any sizeable amount of data - you'll notice that queries can be _extremely_ slow which is inherent to the use of EAV data structures. In terms of sql, it changes this:

    SELECT 
        posts.*,
        posts_title_translations.title,
        posts_title_translations.content,
        etc.
    FROM
        posts
    LEFT JOIN
        i18n as posts_title_translations ON (
            posts_title_translations.locale = "xx" AND
            posts_title_translations.model = "Posts" AND
            posts_title_translations.foreign_key = posts.id AND
            posts_title_translations.field = 'title'
       )
    LEFT JOIN
        i18n as posts_body_translations ON (
            posts_body_translations.locale = "xx" AND
            posts_body_translations.model = "Posts" AND
            posts_body_translations.foreign_key = posts.id AND
            posts_body_translations.field = 'body'
       )
    etc.

Into:

    SELECT 
        posts.*,
        posts_translations.*
    FROM
        posts
    LEFT JOIN
        posts_translations ON (
            posts_translations.locale = "xx" AND
            posts_translations.id = posts.id
    )
    // no etc.

It should be clear at a glance that the executed queries are simpler, can take advantage of better indexing (because everything is _not_ dumped in a single mediumtext field), and doesn't become more complicated with more translated fields.

This also brings with it benefits such as being much easier to search for translated content, as there are no hoops to jump through (as, with some very you search for `PostsTranslation.title` = "Le Title"` and get the translated record found).

**Comment by Spriz** [comment]
Thanks @AD7six - now we're a few months ahead, and I just found out what you mean by "effective"...

## From #cakephp
```
[15:50:25]  <spriz>	Does anyone have experience in bad (!) performance with TranslateBehaviour? A quey goes from ~20 ms to 12 seconds because of it being translated content :P
[15:50:44]  <ADmad>	spriz: use ShadowTranslate
[15:50:53]  <ADmad>	~tell spriz about shadowtranslate
[15:50:54]  <CakeBot>	spriz: shadowtranslate is https://github.com/AD7six/cakephp-shadow-translate/issues/15#issuecomment-122660668
[15:51:08]  <spriz>	....
[...]
[15:51:10]  <spriz>	you got me there
[15:51:23]  <spriz>	ADmad: See who wrote that issue in July
```

Time to migrate!
